Integer quantidade
string endereço
flout combustivel
Boolean estadoDeiluminação
real cepCompleto
real andarElevador
Boolean ledElevador
string dataNiverMoises
real pesoPrato
real boisfazenda
